services:
  ds-logger:
    build: ./ds-logger
    depends_on:
      - redis-queue
      - consul
    networks:
      - default
  redis-queue:
    image: redis:latest
    container_name: redis-queue
    ports:
      - "6380:6379"
    networks:
      - default

  consul:
    image: hashicorp/consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0

  redis-primary:
    image: redis:latest
    hostname: db-primary

  redis-replica:
    image: redis:latest
    command: ["redis-server", "--replicaof", "db-primary", "6379"]
    deploy:
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis-replica.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.redis-replica.entrypoints=redis"
      - "traefik.tcp.services.redis-replica.loadbalancer.server.port=6379"

  web:
    build: ./web
    depends_on:
      - redis-queue
      - consul
    deploy:
      replicas: 3
    networks: [default]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`) && PathPrefix(`/`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=3000"

  traefik:
    image: traefik:v3.0
    command:
      - --api.dashboard=true
    ports:
      - "80:80"
      - "8080:8080" # dashboard
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        aliases:
          - db-replica
