services:
  consul:
    image: hashicorp/consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0

  registrator:
    #image: metabrainz/serviceregistrator:latest
    image: ghcr.io/rizerphe-student/serviceregistrator:edge
    command: --ip 172.17.0.1 --consul-host consul --consul-port 8500 --debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - consul

  redis-primary:
    image: redis:latest
    hostname: redis-primary
    expose:
      - "6379"
    environment:
      SERVICE_NAME: redis-primary
      SERVICE_TAGS: primary
    networks:
      - backend

  redis-replica:
    image: redis:latest
    command: ["redis-server", "--replicaof", "redis-primary", "6379"]
    expose:
      - "6379"
    environment:
      SERVICE_NAME: redis-replica
      SERVICE_TAGS: replica
    deploy:
      replicas: 3
    networks:
      - backend

  web:
    image: nginx:alpine # TODO: change
    deploy:
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"

  traefik:
    image: traefik:v3.0
    command:
      - --api.dashboard=true
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - consul

networks:
  backend:
